apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
  namespace: default
data:
  loki-config.yaml: |
    auth_enabled: false

    server:
      http_listen_port: 3100

    ingester:
      wal:
        enabled: false

    schema_config:
      configs:
        - from: 2025-05-01
          store: filesystem
          schema: v11
          index:
            prefix: index_
            period: 24h  # меньший период для теста

    storage_config:
      filesystem:
        directory: /tmp/loki/chunks

    compactor:
      retention_enabled: true
      retention_delete_delay: 2m
      #retention_period: 1h  # удалить данные старше

    limits_config:
      retention_period: 1h  # Глобально удалить старше 1ч
      enforce_metric_name: false
      reject_old_samples: true
      reject_old_samples_max_age: 1h

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      containers:
        - name: loki
          image: grafana/loki:2.9.0
          args:
            - -config.file=/etc/loki/loki-config.yaml
            - -config.expand-env=true
          ports:
            - containerPort: 3100
          volumeMounts:
            - name: config
              mountPath: /etc/loki
            - name: index
              mountPath: /tmp/loki/index
            - name: cache
              mountPath: /tmp/loki/cache
            - name: chunks
              mountPath: /tmp/loki/
            - name: loki-storage
              mountPath: /var/loki
      volumes:
        - name: config
          configMap:
            name: loki-config
        - name: index
          emptyDir: {}
        - name: cache
          emptyDir: {}
        - name: chunks
          emptyDir: {}
        - name: loki-storage
          emptyDir: {}

---

apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: default
spec:
  type: NodePort
  selector:
    app: loki
  ports:
    - protocol: TCP
      port: 3100
      targetPort: 3100
      nodePort: 31031
