auth_enabled: false

server:
  http_listen_port: 3100

ingester:
  wal:
    enabled: false

schema_config:
  configs:
    - from: 2025-05-01
      store: boltdb-shipper
      schema: v11
      index:
        prefix: index_
        period: 1h              # меньший период для теста

storage_config:
  boltdb_shipper:
    active_index_directory: /tmp/loki/index
    cache_location: /tmp/loki/cache
    shared_store: filesystem

  filesystem:
    directory: /tmp/loki/chunks

compactor:
  retention_enabled: true
  retention_delete_delay: 2m
  retention_period: 1h          # удалить данные старше 
  

limits_config:
  retention_period: 1h           # глобально лимит хранения
