---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-exporter
  labels:
    app: node-exporter
spec:
  selector:
    matchLabels:
      app: node-exporter
  template:
    metadata:
      labels:
        app: node-exporter
    spec:
      hostNetwork: true   # node-exporter слушает на хост-сети
      containers:
        - name: node-exporter
          image: prom/node-exporter:latest
          args:
            - --path.rootfs=/host/root
            - --path.procfs=/host/proc
            - --path.sysfs=/host/sys    
            - --collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($|/)"        
          ports:
            - containerPort: 9100
              hostPort: 9100
          volumeMounts:
            - name: rootfs
              mountPath: /host/root
              readOnly: true
            - name: procfs
              mountPath: /host/proc
              readOnly: true
            - name: sysfs
              mountPath: /host/sys
              readOnly: true
      volumes:
        - name: rootfs
          hostPath:
            path: /
            type: Directory
        - name: procfs
          hostPath:
            path: /proc
            type: Directory
        - name: sysfs
          hostPath:
            path: /sys
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: node-exporter
  labels:
    app: node-exporter
spec:
  selector:
    app: node-exporter
  ports:
    - port: 9100
      targetPort: 9100
#  clusterIP: None  # Headless-сервис
      nodePort: 30100
  type: NodePort 

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'node-exporter'
        static_configs:
          - targets:
              - localhost:9100
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: prometheus
  labels:
    app: prometheus
spec:
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      hostNetwork: true
      containers:
        - name: prometheus
          image: prom/prometheus:latest
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus"
            - "--web.listen-address=:9090"
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: prometheus-config
              mountPath: /etc/prometheus/
            - name: prometheus-data
              mountPath: /prometheus
      volumes:
        - name: prometheus-config
          configMap:
            name: prometheus-config
        - name: prometheus-data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
spec:
  type: NodePort
  selector:
    app: prometheus
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
      nodePort: 30090

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vector-config
data:
  vector.toml: |
    [sources.logs]
    type = "file"
    include = ["/var/log/current-time/*.log"]
    start_at_beginning = true


    [sinks.loki]
    type = "loki"
    inputs = ["logs"]
    endpoint = "http://host.minikube.internal:3100"
    encoding.codec = "json"

    [sinks.loki.labels]
    job = "current-time"

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: vector
  labels:
    app: vector
spec:
  selector:
    matchLabels:
      app: vector
  template:
    metadata:
      labels:
        app: vector
    spec:
      containers:
        - name: vector
          image: timberio/vector:0.27.0-debian
          args: ["-c", "/etc/vector/vector.toml"]
          volumeMounts:
            - name: vector-config
              mountPath: /etc/vector
            - name: varlog
              mountPath: /var/log/current-time
            - name: varlogpods
              mountPath: /var/log/pods
              readOnly: true
      volumes:
        - name: vector-config
          configMap:
            name: vector-config
        - name: varlog
          hostPath:
            path: /var/log/current-time
            type: DirectoryOrCreate
        - name: varlogpods
          hostPath:
            path: /var/log/pods
            type: Directory

