apiVersion: v1
kind: Service
metadata:
  name: node-exporter-service
spec:
  selector:
    app: current-time             # Предполагается, что метка app=current-time есть у подов с node-exporter
  ports:
    - protocol: TCP
      port: 9100                 # Внутренний порт сервиса
      targetPort: 9100           # Порт на контейнере node-exporter
      nodePort: 31100            # Внешний порт на нодах minikube (в диапазоне 30000-32767)
  type: NodePort
