# [sources.kubernetes_logs]
# type = "file"
# include = ["/var/log/pods/*/*/current-time/*.log"]
# ignore_older = 86400

[sources.kubernetes_logs]
type = "file"
include = ["/var/log/pods/*/*/current-time/*.log"]
ignore_older = 86400

[sinks.loki]
type = "loki"
inputs = ["kubernetes_logs"]
endpoint = "http://host.minikube.internal:3100"
encoding.codec = "json"

[sinks.loki.labels]
job = "current-time"

