apiVersion: v1
kind: ConfigMap
metadata:
  name: vector-config
data:
  vector.toml: |
    [sources.logs]
    type = "file"
    include = ["/var/log/current-time/*.log"]

    [sinks.loki]
    type = "loki"
    inputs = ["logs"]
    endpoint = "http://host.minikube.internal:3100"
    encoding.codec = "json"

    [sinks.loki.labels]
    job = "current-time"
