name: Build and Push Docker Image

on:
  push:
    branches: [ main ]

jobs:
  docker:
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/current-time:latest

      - name: Run app in background
        run: |
          sudo docker image prune -f
          docker stop ${{ secrets.DOCKERHUB_USERNAME }}/current-time
          docker image rm $(docker images "${{ secrets.DOCKERHUB_USERNAME }}/current-time" --format "{{.Repository}}:{{.Tag}}" | grep -v latest) 2>/dev/null || true
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/current-time:latest
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/current-time:latest
          docker run -d -p 1001:1001 ${{ secrets.DOCKERHUB_USERNAME }}/current-time

